version: '3'

services:
  frontend:
    build: .
    expose:
      - 80
    labels:
      traefik.enable: "true"
      traefik.http.routers.fourinarow-app.rule: "Host(`play.fourinarow.ffactory.me`)"
      traefik.http.routers.fourinarow-app.entrypoints: "https"
      traefik.http.routers.fourinarow-app.tls: "true"
      traefik.http.routers.fourinarow-app.tls.certresolver: "letsencrypt"
      traefik.http.services.fourinarow-app.loadbalancer.server.port: "80"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik_proxy